# Generated by Django 2.2.2 on 2019-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0009_auto_20190605_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility', models.CharField(max_length=255)),
                ('fields', models.TextField()),
                ('target', models.ForeignKey(on_delete='cascade', to='tom_targets.Target')),
            ],
            options={
                'unique_together': {('name', 'target', 'facility')},
            },
        ),
    ]
