# Generated by Django 2.2.2 on 2019-06-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0004_auto_20190626_0904'),
        ('tom_education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelapseDataProduct',
            fields=[
                ('dataproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tom_dataproducts.DataProduct')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], max_length=10)),
                ('frames', models.ManyToManyField(related_name='timelapse', to='tom_dataproducts.DataProduct')),
            ],
            bases=('tom_dataproducts.dataproduct',),
        ),
    ]
