# Generated by Django 2.2.2 on 2019-06-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0002_timelapsedataproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelapsedataproduct',
            name='fmt',
            field=models.CharField(choices=[('gif', 'GIF'), ('mp4', 'MP4'), ('webm', 'WebM')], default='gif', max_length=10),
        ),
        migrations.AddField(
            model_name='timelapsedataproduct',
            name='fps',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='timelapsedataproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
