# Generated by Django 2.2.2 on 2019-06-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0003_auto_20190627_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelapsedataproduct',
            name='failure_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
