# Generated by Django 2.2.2 on 2019-07-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0010_merge_20190612_1227'),
        ('tom_education', '0004_timelapsedataproduct_failure_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('target', models.ForeignKey(null=True, on_delete='cascade', to='tom_targets.Target')),
            ],
        ),
        migrations.RemoveField(
            model_name='timelapsedataproduct',
            name='failure_message',
        ),
        migrations.RemoveField(
            model_name='timelapsedataproduct',
            name='status',
        ),
        migrations.CreateModel(
            name='TimelapseProcess',
            fields=[
                ('asyncprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tom_education.AsyncProcess')),
                ('timelapse_product', models.ForeignKey(on_delete='cascade', to='tom_education.TimelapseDataProduct')),
            ],
            bases=('tom_education.asyncprocess',),
        ),
    ]
