# Generated by Django 2.2.2 on 2019-07-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0005_auto_20190710_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncprocess',
            name='identifier',
            field=models.CharField(default='i', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
