# Generated by Django 2.2.2 on 2019-07-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0006_asyncprocess_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncprocess',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
        migrations.AlterField(
            model_name='observationtemplate',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
        migrations.AlterField(
            model_name='timelapseprocess',
            name='timelapse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_education.TimelapseDataProduct'),
        ),
    ]
