# Generated by Django 2.2.2 on 2019-07-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0008_autovarprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncprocess',
            name='terminal_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
