# Generated by Django 2.2.2 on 2019-07-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0009_asyncprocess_terminal_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncprocess',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tom_targets.Target'),
        ),
    ]
