# Generated by Django 2.2.2 on 2019-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0010_auto_20190711_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autovarprocess',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
