# Generated by Django 2.2.2 on 2019-07-12 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0011_auto_20190711_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncprocess',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
