# Generated by Django 2.2.2 on 2019-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0012_asyncprocess_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncprocess',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
