# Generated by Django 2.2.2 on 2019-07-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_dataproducts', '0005_auto_20190704_1010'),
        ('tom_targets', '0010_merge_20190612_1227'),
        ('tom_education', '0014_autovarprocess_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutovarProcess',
            new_name='PipelineProcess',
        ),
        migrations.CreateModel(
            name='AutovarProcess',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tom_education.pipelineprocess',),
        ),
    ]

    atomic = False
