# Generated by Django 2.2.2 on 2019-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0015_auto_20190715_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineprocess',
            name='input_files',
            field=models.ManyToManyField(related_name='pipeline', to='tom_dataproducts.DataProduct'),
        ),
    ]
