# Generated by Django 2.2.2 on 2019-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0016_auto_20190715_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineprocess',
            name='flags_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
