# Generated by Django 2.2.2 on 2019-07-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_education', '0017_pipelineprocess_flags_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutovarProcess',
        ),
    ]
